project:
  type: website
  output-dir: "docs"

website:
  title: "AC-2023"
  site-url: https://fcpys.github.io/ac2023/
  repo-url: https://github.com/fcpys/ac2023/
  repo-branch: main
  repo-actions: [edit, issue]
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: equipo.qmd
        text: Equipo docente
      - href: about.qmd
        text: Programa 
      - href: clases.qmd
        text: Clases 
  sidebar:
    style: "floating"
    search: true
    contents:
      - section: "Instalar R"
        contents:
          - instala.qmd
      - section: "Talleres"
        contents:
          - P1.qmd


format:
  html:
    theme: 
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true

editor: visual

